---
title: 2014×3 – Transcriptional correlates of long-term habituation
date: '2014-12-16T15:17:25'
categories:
- News
- Publications - Bob
- Publications - Irina
- ▼ Publications - Students
---

Third paper of the year for the lab (gasp!) is now out in *Learning and Memory* [cite source=’doi’]10.1101/lm.036970.114[/cite].

The focus of the project is habituation, considered the simplest and most ancient form of memory. Long-term habituation requires changes in gene expression, but to date there is almost nothing known about what specific changes are required to encode and store a long-term habituation memory.

We’re not the first to try to tackle this issue, but it turns out to be a very difficult topic for study. Habituation is typically very site specific, occurring only at the site of training. This implies a relatively discrete set of neurons encode the memory, and that presents a real problem for qPCR and microarray analysis, because the signal from memory-encoding neurons could easily be washed out from signal from non-encoding neurons, glia, etc.

Our strategy was to develop a new, automated protocol for inducing long-term habituation over the entire body of an *Aplysia*. With the help of a tinker-toy set, a windshield-wiper motor, a relay box, an old computer with a parallel port, and some qBASIC programming (blast from the bast), we developed a slug car wash–an apparatus we could place over the tanks to repeatedly (though gently) brush Aplysia without any need for human intervention during training. We made a video to show off the system, which you can see [here](https://www.youtube.com/watch?v=LcpOvH2x-3g&list=UUdbz9_sPiV8ueIDk1szSy8w "Slug Car Wash").

The slug car wash turns out to work great. We tracked the development of habituation over repeated rounds of training and saw a classic pattern of behavior–robust decreases in behavior at the end of each round of training, substantial overnight recovery (forgetting), but a progressive development of a persistently decreased response within 3 days of training. Importantly, we could observe habituated responding when stimulating the animal at the head, the siphon, or the tail. Moreover, the effect sizes were *huge*. So it was pretty clear that the slug car wash was producing the high impact we were looking for. In addition, we found that pattern of training really does matter–when training has breaks between sessions and is spaced out over 3 days it is extremely effective; massing all the same stimulation together into a single one-day session (at a slightly higher rate to squeeze it all in) produced neither long-term nor short-term habituation. This is a useful finding because it gave us an additional no-memory control, one which could ensure any molecular correlates identified are specific to memory formation, not just to the activity induced by brushing.

So what’s changing transcriptionally? We decided to focus on the pleural ganglia containing the VC nociceptors. These are relatively high-threshold neurons, and are probably not carrying the bulk of the activity induced by the brush. Unfortunately, though, no one yet knows \*where\* in the Aplysia nervous system to find the cell bodies of the low-threshold neurons that mediate light touch (probably in the periphery). Not to worry, though–we did record from the VCs in reduced preps and found that they do actually get some activation from the brush: about 1/4 fired APs, and most of the rest got lots of IPSPs from off-center stimulation.

To track transcriptional changes, we used the custom-designed microarray we recently developed in the lab [cite source=’pubmed’]25117657[/cite]. Some quick words about methods: We again used a large-ish sample size (n=8/group; can you believe that n=3/group is still common in microarray!?). We also used very high statistical standards by adopting the ‘treat’ function in limma which allows you to specify a reasonable null hypothesis (e.g. at least 10% regulation in either direction, rather than the standard practice of testing against a null of no regulation). Adopting a more reasonable null enables you to test for statistical and practical significance *at the same time*, and we’ve found that transcripts which pass such a rigorous test generalize very well to new samples. We’ve been finding R and limma surprisingly easy to use, which is pretty fantastic for free software.

Anyways, back to the data. The microarray results were a bit of a bummer. Out of over 20,000 transcripts tested, only \*one\* came up as strongly regulated. Bummer. Another 20 transcripts came up as regulated if you use a standard null hypothesis, but, as expected, none of these validated.

Although the microarray results were not what we hoped, we did further explore the one regulated transcript, and it turns out to be quite interesting. From sequence alignment, it seems to be an *Aplysia* homolog of cornichon, an auxiliary subunit for AMPA receptors. In invertebrates, cornichon seems to limit trafficking to AMPA receptors to the membrane and therefore reduces glugatmate-induced currents[cite source=’pubmed’]24094107[/cite]. Note that this is precisely the type of effect that could produce behavioral habituation. Moreover, one of the few known molecular correlates of long-term habituation is a decrease in surface expression of glutamate receptors [cite source=’pubmed’]14573539[/cite]. Fits perfectly!

To ensure that cornichon is truly regulated in our paradigm, we did some additional follow-ups. First, we used qPCR to check cornichon levels not only in the microarray samples but in an additional, independent set of samples. Sure enough, we confirmed up-regulation of cornichon in the pleural ganglia 1 day after training. In addition, we checked levels in massed animals, who display no memory after training. In this case, cornichon was actually slightly down, and was significantly different than in the regularly trained animals. So, cornichon is quite specifically and consistently up-regulated after long-term habituation training. As far as we know, this is the first specific transcriptional correlate of long-term habituation to be identified.

Needless to say, we’re quite proud of this work. It wouldn’t have been possible without two of the most talented undergrads we’ve had in the lab: Geraldine Holmes and Samantha (Sami) Herdegen. Geraldine was the most diligent slug trainer in the history of the lab. For this paper alone she ran over 48 animals, testing each 8 times a day for 3-5 days–that’s a whole lot of behavior to monitor! Sami, of course, has been the qPCR wizard in the lab, testing lots and lots and lots and lots of transcripts for regulation. It’s no surprise that both are on to bigger and better things, Geraldine is now in a PhD program in Canada and Sami is soon to start pharmacy school. We also had contributions from John Schuon (when he could fight his way in for some qPCR; now off to medical school), Ashly Cyriac (who helped start the project before heading off to pharmacy school), Jamie Lass and Catherine Conte. Congrats!

As has now become the norm for the lab, all the raw data from this study been posted online at the Open Science Framework: <https://osf.io/6ew4i/>.