---
title: Behavioral adaptation of the Aplysia siphon-withdrawal response is accompanied
  by sensory adaptation
date: '2007-01-27T06:08:33'
categories:
- Publications - Bob
---

Calin-Jageman RJ, Fischer TM

Behav. Neurosci. 2007 Feb;121(1):200-11

PMID: [17324064](http://www.ncbi.nlm.nih.gov/pubmed/17324064)

## Abstract

Behavioral adaptation is a decrease in behavioral responsiveness due to a sustained stimulus and is a key component to an organism’s overall adjustment to its ambient environment. The authors examined the relationship between behavioral adaptation and sensory adaptation in the siphon-withdrawal reflex (SWR) of Aplysia californica. Sensory input to the SWR circuit was measured via en passant extracellular recordings from the siphon nerve in semi-intact preparations. The authors characterized sensory activity in response to water turbulence, an ethologically relevant stimulus that produces behavioral adaptation of the SWR. The authors found that water turbulence elicits a continuous sensory response that adapts to a low-level steady state. Consistent with behavioral measures, this sensory adaptation attenuates the evoked response to siphon taps delivered during water turbulence. Comparing trends in both behavioral and sensory adaptation revealed similar dynamics during turbulence but divergent trends during recovery. Specifically, behavioral recovery was inversely related to the duration of environmental change; recovery of sensory adaptation was not. This supports the authors’ hypothesis that environment-driven behavioral adaptation reflects an interaction between sensory adaptation and additional dynamic processes.